// Generated by CoffeeScript 1.6.2
(function() {
  var check_email, cheerio, fetch_email, get_email, get_link, get_link_poll, get_list, gn, make_post_request, make_request, q, qs, request, set_email, _;

  qs = require('querystring');

  q = require('q');

  request = require('request');

  _ = require('lodash');

  cheerio = require('cheerio');

  make_request = function(params) {
    var base_url, deferred, request_url;

    deferred = q.defer();
    base_url = 'https://www.guerrillamail.com/ajax.php';
    request_url = base_url + '?' + qs.stringify(params);
    request(request_url, function(error, response, body) {
      if (response.statusCode !== 200) {
        return deferred.reject(response.statusCode);
      } else {
        return deferred.resolve(JSON.parse(body));
      }
    });
    return deferred.promise;
  };

  make_post_request = function(params, data) {
    var base_url, deferred, request_url;

    deferred = q.defer();
    base_url = 'https://www.guerrillamail.com/ajax.php';
    request_url = base_url + '?' + qs.stringify(params);
    request.post(request_url, {
      form: data
    }, function(error, response, body) {
      if (response.statusCode === 200) {
        return deferred.resolve(JSON.parse(body));
      } else {
        return deferred.reject(error);
      }
    });
    return deferred.promise;
  };

  get_email = function() {
    return make_request({
      f: 'get_email_address',
      lang: 'en'
    });
  };

  set_email = function(token, email, domain) {
    return make_post_request({
      f: 'set_email_user'
    }, {
      email_user: email,
      sid_token: token,
      domain: domain
    });
  };

  check_email = function(token) {
    return make_request({
      f: 'check_email',
      sid_token: token,
      seq: 0
    });
  };

  get_list = function(token) {
    return make_request({
      f: 'get_email_list',
      sid_token: token,
      offset: 0
    });
  };

  fetch_email = function(token, email_id) {
    return make_request({
      f: 'fetch_email',
      sid_token: token,
      email_id: email_id
    });
  };

  get_link = function(subject, contains_text, token) {
    var link_text;

    link_text = q.defer();
    gn.get_list(token).then(function(data) {
      var email_object;

      email_object = _.find(data.list, {
        mail_subject: subject
      });
      if (email_object != null) {
        return email_object['mail_id'];
      } else {
        return link_text.reject('no_matching_email');
      }
    }).then(function(email_id) {
      return gn.fetch_email(token, email_id).then(function(data) {
        var $;

        $ = cheerio.load(data.mail_body);
        return link_text.resolve($("a:contains(" + contains_text + ")").text());
      });
    }, function(error) {
      return link_text.reject(error);
    });
    return link_text.promise;
  };

  get_link_poll = function(subject, contains_text, token) {
    var link;

    link = q.defer();
    get_link(subject, contains_text, token).then(function(email) {
      return link.resolve(email);
    }, function(error) {
      if (error === 'no_matching_email') {
        return setTimeout(function() {
          return link.resolve(get_link_poll(subject, contains_text, token));
        }, 1500);
      } else {
        return link.reject(error);
      }
    });
    return link.promise;
  };

  gn = {
    get_email: get_email,
    set_email: set_email,
    check_email: check_email,
    fetch_email: fetch_email,
    get_list: get_list,
    get_link: get_link,
    get_link_poll: get_link_poll
  };

  module.exports = gn;

}).call(this);
